name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
    - '**.go'
    - 'go.mod'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.1.0

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go test -v ./...
